const bilingual = (en, zh) => `<span lang="en">${en}</span><span lang="zh-CN">${zh}</span>`;
export const pages = [
{slug:'identity',title:'Visual identity · 视觉系统',chapter:'03',body:`
<header class="chapter-intro identity-intro">
<p class="eyebrow">03 / VISUAL IDENTITY <span lang="zh-CN">视觉系统</span></p>
<h1 class="display"><span lang="en">A quiet field.<br>A clear signal.</span><span lang="zh-CN">深处有场，感知有光。</span></h1>
<div class="lede"><p class="en" lang="en">Depth makes room for observation. Sense marks the moment something becomes understood.</p><p class="zh" lang="zh-CN">Depth 为观察留出空间。Sense 标记被感知、被读懂的瞬间。</p></div>
<a class="text-link" href="#logo-lab">Explore the identity <span lang="zh-CN">探索视觉系统</span> ↓</a>
</header>
<section class="section logo-section" id="logo-lab" aria-labelledby="logo-heading">
<div class="section-heading"><p class="eyebrow">01 / THE SIGNATURE</p><h2 id="logo-heading">${bilingual('One identity. Different contexts.', '一种识别，进入不同场景。')}</h2></div>
<div class="logo-lab">
<div class="logo-stage" id="logo-stage" data-tone="dark"><span class="stage-index">D / 01</span><img id="logo-preview" src="assets/logo-light.svg" alt="DiFluid primary logo on a dark background" width="640" height="220"><span class="stage-bottom">DiFluid / IDENTITY EXPLORER</span></div>
<div class="logo-controls panel">
<p class="caption">LIVE PREVIEW <span lang="zh-CN">标志预览</span></p>
<fieldset><legend>Signature <span lang="zh-CN">标志版本</span></legend><div class="choice-row"><button type="button" class="choice" data-logo="primary" aria-pressed="true">Primary <span lang="zh-CN">主标志</span></button><button type="button" class="choice" data-logo="monochrome" aria-pressed="false">Monochrome <span lang="zh-CN">单色标志</span></button></div></fieldset>
<fieldset><legend>Surface <span lang="zh-CN">展示背景</span></legend><div class="choice-row"><button type="button" class="choice" data-logo-tone="dark" aria-pressed="true">Depth <span lang="zh-CN">深色</span></button><button type="button" class="choice" data-logo-tone="light" aria-pressed="false">Light <span lang="zh-CN">浅色</span></button></div></fieldset>
<div class="logo-context" aria-live="polite"><p id="logo-context-en" class="en" lang="en">The primary wordmark pairs the DiFluid name with a small Sense accent. Keep its proportions and original artwork intact.</p><p id="logo-context-zh" class="zh" lang="zh-CN">主字标以 DiFluid 名称与少量 Sense 点缀建立识别，保留原始比例与图形。</p></div>
<p class="caption" lang="en">Light is a logo sample surface. Use the original artwork; refer to the VI master for clear-space and minimum-size specifications.</p><p class="caption" lang="zh-CN">浅色仅用于标志展示。请使用原始图形，安全留白与最小尺寸以 VI 母版为准。</p>
</div></div>
<div class="signature-wordmark"><p class="caption">THE CLAIM <span lang="zh-CN">品牌主张</span></p><div class="wordmark-sample"><img src="assets/wordmark.svg" alt="Coffee, understood." loading="lazy" width="520" height="140"></div><p class="caption" lang="en">The original brand claim artwork, presented in its original proportions.</p><p class="caption" lang="zh-CN">官方品牌主张图形，保留原始比例呈现。</p></div>
</section>
<section class="section motion-section" aria-labelledby="motion-heading">
<div class="section-heading"><p class="eyebrow">02 / IDENTITY IN MOTION</p><h2 id="motion-heading">${bilingual('Recognition, unfolding.', '让识别，逐渐发生。')}</h2><p class="en" lang="en">Experience the existing logo animation. Playback starts only when you choose.</p><p class="zh" lang="zh-CN">观看现有 Logo 动效，自主决定播放节奏。</p></div>
<div class="motion-stage"><video id="logo-motion" controls playsinline preload="metadata" poster="assets/motion-poster.webp" aria-label="DiFluid logo animation / DiFluid 标志动效"><source src="assets/logo-motion.mp4" type="video/mp4">Your browser does not support video playback. 当前浏览器不支持视频播放。</video></div>
<div class="motion-toolbar"><div class="choice-row"><button type="button" class="button" id="motion-toggle">Play <span lang="zh-CN">播放</span></button><button type="button" class="button" id="motion-restart">Replay <span lang="zh-CN">重播</span></button></div><p class="caption" id="motion-status" aria-live="polite">Ready to play · 等待播放</p></div>
</section>
<section class="section color-section" aria-labelledby="color-heading">
<div class="section-heading"><p class="eyebrow">03 / DEPTH × SENSE</p><h2 id="color-heading">${bilingual('The field. The signal.', '以深度为场，以感知为信号。')}</h2></div>
<div class="color-composition" aria-label="Depth and Sense color composition"><div class="color-field"><span>DEPTH</span><span class="caption">A field for understanding<br><span lang="zh-CN">承载理解的场</span></span></div><div class="sense-line"></div><div class="color-signal"><span class="sense-dot"></span><p>SENSE<br><span lang="zh-CN">一束洞察</span></p></div></div>
<p class="en" lang="en">A mostly neutral environment brings structure into focus. A small, precise use of Sense marks a selection, a detection, or an insight.</p><p class="zh" lang="zh-CN">近乎无色的环境，让结构与细微差异浮现。少量而精确的 Sense，指向选中、检测或洞察。</p>
<div class="token-grid" role="group" aria-label="Explore brand color tokens / 浏览品牌色值">
<button type="button" class="token-card" style="--swatch:#0A0D10" data-token="depth10" aria-pressed="true"><span class="token-swatch"></span><span>Depth / 10</span><code>#0A0D10</code></button>
<button type="button" class="token-card" style="--swatch:#15191D" data-token="depth20" aria-pressed="false"><span class="token-swatch"></span><span>Depth / 20</span><code>#15191D</code></button>
<button type="button" class="token-card" style="--swatch:#22282E" data-token="depth30" aria-pressed="false"><span class="token-swatch"></span><span>Depth / 30</span><code>#22282E</code></button>
<button type="button" class="token-card" style="--swatch:#F3F4F5" data-token="depth100" aria-pressed="false"><span class="token-swatch"></span><span>Depth / 100</span><code>#F3F4F5</code></button>
<button type="button" class="token-card" style="--swatch:#5ECDBD" data-token="sense50" aria-pressed="false"><span class="token-swatch"></span><span>Sense / 50</span><code>#5ECDBD</code></button>
</div>
<div class="token-detail panel" aria-live="polite"><p class="caption" id="token-property">--brand-depth-10</p><p class="en" id="token-description-en" lang="en">Depth / 10 provides the quiet background field. It lets imagery, information, and the signal take precedence.</p><p class="zh" id="token-description-zh" lang="zh-CN">Depth / 10 构成安静的背景场，让图像、信息与信号成为关注中心。</p></div>
<p class="caption" lang="en">Foundational colors in the DiFluid visual system. Interface colors also need roles that explain states and actions.</p><p class="caption" lang="zh-CN">DiFluid 视觉系统的基础色阶。进入界面后，颜色还需对应清晰的状态与操作含义。</p>
</section>
<section class="section type-section" aria-labelledby="type-heading">
<div class="section-heading"><p class="eyebrow">04 / TYPE AS A TOOL</p><h2 id="type-heading">${bilingual('Clarity has a rhythm.', '清晰，自有节奏。')}</h2><span class="tag">DiFluid Mona / Noto Sans CJK</span></div>
<div class="type-specimen"><p class="type-display" lang="en">Coffee,<br>understood.</p><p class="type-chinese" lang="zh-CN">读懂咖啡。</p><div class="type-footer"><span>Aa / 永</span><span>0123456789</span><span>Observation → Understanding</span></div></div>
<div class="grid-3 type-notes"><div><h3>${bilingual('Expressive headlines', '标题，表达主张')}</h3><p class="en" lang="en">A short idea, given enough room to be remembered.</p><p class="zh" lang="zh-CN">用简短的想法与充足的留白，形成记忆。</p></div><div><h3>${bilingual('Bilingual by design', '中英，同步可读')}</h3><p class="en" lang="en">Two languages share the meaning without competing for attention.</p><p class="zh" lang="zh-CN">两种语言共同传达含义，以层级协调阅读。</p></div><div><h3>${bilingual('Information first', '信息，优先清晰')}</h3><p class="en" lang="en">Use stable numerals and a clear distinction between values and labels.</p><p class="zh" lang="zh-CN">数字保持稳定，数值与标签清晰区分。</p></div></div>
<p class="caption" lang="en">The VI names Mona Sans as “DiFluid Mona” for Latin typography and Noto Sans CJK for Chinese. This web specimen adapts that direction to responsive reading.</p><p class="caption" lang="zh-CN">VI 以 Mona Sans（品牌内名 DiFluid Mona）承担拉丁字母，以思源黑体 Noto Sans CJK 承担中文。本网页样张将这一方向适配为响应式阅读。</p>
</section>
<section class="section assertion"><p class="eyebrow">AN IDENTITY PRINCIPLE</p><h2>${bilingual('Let the insight be<br>the brightest thing.', '让洞察，成为最亮的部分。')}</h2><a class="text-link" href="applications.html">See the identity in use <span lang="zh-CN">进入应用场景</span> ↗</a></section>
`},
{slug:'applications',title:'Applications · 品牌应用',chapter:'04',body:`
<header class="chapter-intro"><p class="eyebrow">04 / BRAND IN THE WORLD <span lang="zh-CN">品牌应用</span></p><h1 class="display">${bilingual('An identity you<br>can live with.', '让识别，进入日常。')}</h1><div class="lede"><p class="en" lang="en">From a coffee ritual to a shared space. A coherent identity stays recognizable as the surface changes.</p><p class="zh" lang="zh-CN">从一杯咖啡的日常，到共同体验的空间。载体可以变化，识别保持连贯。</p></div><a class="text-link" href="#application-gallery">Explore the applications <span lang="zh-CN">浏览应用</span> ↓</a></header>
<section class="section application-gallery" id="application-gallery" aria-labelledby="application-heading"><div class="section-heading"><p class="eyebrow">01 / EVERYDAY PRESENCE</p><h2 id="application-heading">${bilingual('The same idea.<br>A different surface.', '不同载体，同一主张。')}</h2></div>
<div class="application-picker" role="group" aria-label="Select an application / 选择应用场景"><button type="button" class="choice" data-application="mug" aria-pressed="true">01 Mug <span lang="zh-CN">马克杯</span></button><button type="button" class="choice" data-application="pitcher" aria-pressed="false">02 Pitcher <span lang="zh-CN">拉花缸</span></button><button type="button" class="choice" data-application="bottle" aria-pressed="false">03 Bottle <span lang="zh-CN">水瓶</span></button></div>
<figure class="application-figure"><div class="application-image-wrap"><img id="application-image" src="assets/mug.webp" alt="DiFluid mug application visual concept study" width="1600" height="1100" loading="lazy"></div><figcaption class="application-caption"><span id="application-number">01 / 03</span><div aria-live="polite"><h3 id="application-title">Mug <span lang="zh-CN">马克杯</span></h3><p class="en" id="application-description-en" lang="en">A familiar object makes the brand part of the daily coffee ritual. Let the mark remain legible without overwhelming the object.</p><p class="zh" id="application-description-zh" lang="zh-CN">以熟悉的物件融入每日咖啡仪式。标志保持清晰，为器物本身留下空间。</p></div><span class="tag">VI STUDY <span lang="zh-CN">视觉应用稿</span></span></figcaption></figure>
<p class="caption" lang="en">Existing brand application concept visuals. They illustrate identity placement; they are not product availability or manufacturing specifications.</p><p class="caption" lang="zh-CN">现有品牌应用概念视觉，用于讨论品牌落位，不代表产品在售或制造规格。</p></section>
<section class="section" aria-labelledby="material-heading"><div class="section-heading"><p class="eyebrow">02 / A WAY TO CHOOSE</p><h2 id="material-heading">${bilingual('Start with the object.<br>Then make the mark.', '先理解器物，再放置标志。')}</h2><span class="tag">PROPOSED REVIEW LENS <span lang="zh-CN">应用评审提案</span></span></div><div class="grid-3 application-principles"><article class="panel"><span class="caption">01 / MATERIAL</span><h3>${bilingual('Respect the surface.', '尊重材质。')}</h3><p class="en" lang="en">Review contrast on the actual finish. Curvature, reflection, and texture change the way a mark is read.</p><p class="zh" lang="zh-CN">在实际表面检验对比。曲率、反光与纹理，都会影响标志的识读。</p></article><article class="panel"><span class="caption">02 / SCALE</span><h3>${bilingual('Recognizable. Never loud.', '可被识别，无需喧哗。')}</h3><p class="en" lang="en">Judge size at the distance people really use the object. Keep the form and its function in the foreground.</p><p class="zh" lang="zh-CN">以真实使用距离判断尺寸，让器物的形态与功能保持主导。</p></article><article class="panel"><span class="caption">03 / VALIDATION</span><h3>${bilingual('A mockup is a beginning.', '效果图只是起点。')}</h3><p class="en" lang="en">Confirm placement with a physical sample before approving a production process or a durability claim.</p><p class="zh" lang="zh-CN">通过实物打样确认落位，再确定制作工艺与耐用性要求。</p></article></div></section>
<section class="section vehicle-section" aria-labelledby="scale-heading"><div class="section-heading"><p class="eyebrow">03 / BEYOND THE DESK</p><h2 id="scale-heading">${bilingual('Recognition,<br>at another scale.', '在更大的尺度，保持识别。')}</h2></div><figure class="vehicle-figure"><img src="assets/car.webp" alt="DiFluid vehicle identity application concept study" width="1600" height="900" loading="lazy"><figcaption class="caption">EXISTING VI APPLICATION VISUAL <span lang="zh-CN">现有 VI 应用视觉</span></figcaption></figure><div class="split"><p class="en" lang="en">A change in scale asks for a change in composition. The wordmark, the imagery, and the surrounding space still need a clear relationship.</p><p class="zh" lang="zh-CN">尺度的变化，需要构图的调整。字标、图像与周围空间，仍需保持清晰关系。</p></div></section>
<section class="section touchpoints-section" aria-labelledby="touchpoints-heading"><div class="section-heading"><p class="eyebrow">04 / THE NEXT TOUCHPOINTS</p><h2 id="touchpoints-heading">${bilingual('One promise.<br>Many encounters.', '一份承诺，多次相遇。')}</h2><p class="en" lang="en">Directions for future development. Packaging, digital experiences, and exhibition systems still need their own detailed briefs and validation.</p><p class="zh" lang="zh-CN">面向后续发展的方向提案。包装、数字体验与展陈系统，仍需独立的设计任务与验证。</p></div><div class="touchpoint-list"><article class="touchpoint-row"><span class="caption">01</span><div><h3>${bilingual('Packaging → A first understanding', '包装 → 第一次理解')}</h3><p class="en" lang="en">Introduce the product's role, guide the first useful action, and give technical information a readable home.</p><p class="zh" lang="zh-CN">说明产品的作用，引导第一次有效行动，让技术信息各得其所。</p></div><span class="tag">DIRECTION <span lang="zh-CN">方向提案</span></span></article><article class="touchpoint-row"><span class="caption">02</span><div><h3>${bilingual('Digital → A useful next step', '数字体验 → 有帮助的下一步')}</h3><p class="en" lang="en">Bring observation, interpretation, and action together. Use color to explain the state, and language to explain its meaning.</p><p class="zh" lang="zh-CN">连接观察、解释与行动。颜色表达状态，语言解释含义。</p></div><a class="text-link" href="experience.html">Explore <span lang="zh-CN">探索体验</span> ↗</a></article><article class="touchpoint-row"><span class="caption">03</span><div><h3>${bilingual('Exhibition → A shared discovery', '展陈 → 一次共同发现')}</h3><p class="en" lang="en">Let a real coffee experience lead the encounter. Connect what people taste with what the tools help them observe.</p><p class="zh" lang="zh-CN">从真实的咖啡体验出发，把人的品尝与工具带来的观察连接起来。</p></div><span class="tag">DIRECTION <span lang="zh-CN">方向提案</span></span></article></div></section>
<section class="section assertion"><p class="eyebrow">AN APPLICATION PRINCIPLE</p><h2>${bilingual('More than being seen.<br>Being understood.', '不止被看见，更要被读懂。')}</h2><a class="text-link" href="experience.html">From identity to experience <span lang="zh-CN">从识别，走向体验</span> ↗</a></section>
`}
];
